# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a05' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a05
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.5'
    pod "SwiftSpinner"

end
